spring.application.name=orderservice
server.port= 8888

feign.client.default-config.default.decode404=true
spring.cloud.config.enabled=false


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springboot
spring.datasource.username=root
spring.datasource.password=root